#!/usr/bin/python
"""
luckyLUKS is a GUI for creating and (un-)locking LUKS volumes from container files.
For more information visit: http://github.com/jas-per/luckyLUKS

Copyright (c) 2014, Jasper van Hoorn (muzius@gmail.com)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details. <http://www.gnu.org/licenses/>
"""

import locale
import gettext
import os.path
import inspect
from luckyLUKS import main


locale.setlocale(locale.LC_ALL, '')

locale_dir = os.path.join(os.path.dirname(inspect.getsourcefile(main)), 'locale')
translation = gettext.translation('luckyLUKS', locale_dir, fallback=True)

main.luckyLUKS(translation)
